version: "3.8"

services:
  financial:
    build:
      context: .
    environment:
      - API_KEY=${API_KEY}
      - API_URL=${API_URL}
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
    networks:
      - api-tier
      - db-tier
  db:
    image: postgres:13.1
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
      timeout: 20s
      retries: 10
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports: 
      - "5432"
    networks: 
      - db-tier
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
networks: 
  db-tier: {}
  api-tier: {}
